version: '3.8'
services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - app-network

  backend:
    build:
      context: ./RobotBokning
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=RobotBokning;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
      - JWT__SecretKey=superSafeAndSecureKeyThatIsVeryVeryVeryVeryLongAndSecure123456789ABCDEFGHIJKLMNOPQRSTUVWXYZandlittlesafer123
    ports:
      - "5001:8080"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./UI
      dockerfile: Dockerfile
    ports:
      - "3456:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqldata: